const questionBank = [
  {
    id: 1,
    category: 'challenge',
    question: `Bạn thấy tin tuyển dụng lương 30 triệu chỉ cần gõ máy tính làm việc tại Philippines bao vé máy bay đây là dấu hiệu gì? Bạn sẽ làm gì?`,
    answer: `BỎ QUA. Đây là dấu hiệu lừa đảo "việc nhẹ lương cao". Mức lương này bất hợp lý với yêu cầu công việc.`,
  },
  {
    id: 2,
    category: 'challenge',
    question: `Bạn ở Hà Nội, người mới quen trên Facebook rủ đi concert miễn phí 100 phần trăm tại TP Hồ Chí Minh, bạn có đi không?`,
    answer: `TỪ CHỐI. Không đi đến nơi xa với người lạ hoặc mới quen qua mạng. Đây là thủ đoạn dụ dỗ phổ biến nên cần phải kiểm tra kỹ thông tin trước khi thực hiện hành động.`,
  },
  {
    id: 3,
    category: 'challenge',
    question: `Công ty môi giới yêu cầu bạn nộp hộ chiếu gốc để làm thủ tục visa trước khi ký hợp đồng lao động. Hành động này đúng hay sai?`,
    answer: `SAI. Tuyệt đối không giao giấy tờ tùy thân bản gốc cho người lạ khi chưa xác minh rõ pháp lý.`,
  },
  {
    id: 4,
    category: 'challenge',
    question: `Một người quen rủ bạn sang Campuchia thiết kế game online, nói là công việc hợp pháp. Bạn kiểm tra như thế nào?`,
    answer: `Kiểm tra tên công ty, tra cứu trên Google, hỏi ý kiến người thân, liên hệ Cục Quản lý Lao động ngoài nước hoặc Trung tâm dịch vụ việc làm địa phương để được tư vấn.`,
  },
  {
    id: 5,
    category: 'challenge',
    question: `Bạn đăng ký xuất khẩu lao động, người tuyển dụng hối thúc đi ngay trong đêm không cần hộ chiếu, bạn sẽ làm gì vì sao?`,
    answer: `TỪ CHỐI NGAY. Đi nước ngoài không có hộ chiếu là vượt biên trái phép. Việc hối thúc là để bạn không kịp suy nghĩ.`,
  },
  {
    id: 6,
    category: 'challenge',
    question: `Bạn du học làm thêm bị giữ hộ chiếu và ép làm 16 tiếng mỗi ngày, bạn nên làm gì đầu tiên?`,
    answer: `GIỮ BÌNH TĨNH. Tìm cách liên lạc bí mật với Đại sứ quán Việt Nam hoặc nhắn tin định vị cho người thân qua Zalo/Facebook, nhờ hỗ trợ liên hệ với các cơ quan chức năng.`,
  },
  {
    id: 7,
    category: 'challenge',
    question: `Bạn thấy hàng xóm có phụ nữ trẻ bị giám sát, hoảng sợ, nghi bị giam giữ hoặc mua bán người. Bạn cần gọi đường dây nóng nào để báo cáo?`,
    answer: `Gọi 111, Tổng đài Quốc gia về phòng, chống mua bán người, hoặc 113, tổng đài trợ giúp các vấn đề liên quan đến an ninh, trật tự chính đáng của người dân, để báo tin nặc danh.`,
  },
  {
    id: 8,
    category: 'challenge',
    question: `Bạn định ký hợp đồng xuất khẩu lao động nhưng công ty không biển hiệu, văn phòng kín, thu tiền mặt không biên lai. Bạn sẽ làm gì? Vì sao?`,
    answer: `DỪNG GIAO DỊCH. Đây là dấu hiệu công ty lừa đảo. Công ty uy tín phải có trụ sở rõ ràng và tài khoản ngân hàng công ty. Trước khi ký kết, hãy chắc chắn bạn đã nắm rõ các thông tin cần thiết.`,
  },
  {
    id: 9,
    category: 'challenge',
    question: `Người yêu qua mạng, chưa gặp mặt, nhờ bạn nhận giúp một gói hàng từ nước ngoài và phải đóng phí vận chuyển. Bạn sẽ làm gì? Vì sao?`,
    answer: `KHÔNG NHẬN. Đây là chiêu lừa đảo tài chính hoặc vận chuyển hàng cấm, thường dẫn đến việc bị tống tiền hoặc vướng lao lý.`,
  },
  {
    id: 10,
    category: 'challenge',
    question: `Bạn đang đi về quê bằng xe khách thì phát hiện xe không đi đúng lộ trình. Bạn nghi ngờ về hành động này, bạn sẽ làm gì?`,
    answer: `Tìm cớ xin đi vệ sinh hoặc dừng xe ăn uống để bỏ chạy đến nơi đông người hoặc đồn cảnh sát gần nhất.`,
  },
  {
    id: 11,
    category: 'challenge',
    question: `Một người hứa với bạn rằng lo visa tôn giáo sang Hàn Quốc rồi ra ngoài làm việc tự do. Điều này có đúng không?`,
    answer: `SAI PHÁP LUẬT. Visa tôn giáo Hàn Quốc D-6 không được sử dụng trong lao động. Bạn sẽ dễ bị ép làm việc nặng, lương thấp, không được bảo vệ pháp lý.`,
  },
  {
    id: 12,
    category: 'challenge',
    question: `Bạn thấy người quen sang Trung Quốc làm việc lương khủng không hợp đồng, bị yêu cầu nộp giấy tờ tùy thân, bạn sẽ làm gì?`,
    answer: `Cần kiểm tra kỹ thông tin công ty. Luôn giữ giấy tờ tùy thân, tuyệt đối không giao cho bên trung gian. Trong trường hợp không ký hợp đồng lao động nhưng giữ giấy tờ cá nhân thì quyền lợi và nghĩa vụ lao động không được pháp luật bảo đảm. Không ký khi các điều khoản chưa rõ ràng.`,
  },
  {
    id: 13,
    category: 'challenge',
    question: `Một nhóm lao động bị giữ giấy tờ, đe dọa, làm việc quá giờ và bị cấm liên lạc gia đình. Bạn sẽ làm gì?`,
    answer: `Gọi tới tổng đài 111 nếu ở trong lãnh thổ Việt Nam, hoặc cơ quan ngoại giao Việt Nam như Đại sứ quán, Lãnh sự quán nếu ở ngoài nước để báo về tình trạng cưỡng bức lao động.`,
  },
  {
    id: 14,
    category: 'challenge',
    question: `Công ty xuất khẩu lao động yêu cầu nộp 20 triệu tiền "đặt cọc giữ chỗ" vào tài khoản cá nhân của giám đốc. Bạn sẽ làm gì?`,
    answer: `KHÔNG CHUYỂN. Không bao giờ chuyển tiền vào tài khoản cá nhân. Phí xuất khẩu lao động phải có hóa đơn chứng từ rõ ràng của doanh nghiệp.`,
  },
  {
    id: 15,
    category: 'challenge',
    question: `Người môi giới nói: "Cứ sang đó rồi ký hợp đồng sau, bên đó đang cần người gấp". Bạn sẽ làm gì?`,
    answer: `KHÔNG ĐI. Phải ký hợp đồng và tìm hiểu kỹ quyền lợi lao động trước khi xuất cảnh.`,
  },
  {
    id: 16,
    category: 'challenge',
    question: `Bạn nhận được cuộc gọi video từ bạn thân, bạn ấy nói rất ngắn và mắt hay liếc sang bên cạnh, đây là dấu hiệu gì? Bạn sẽ làm gì?`,
    answer: `NGHI VẤN. Có thể cô ấy đang bị khống chế. Hãy hỏi những câu hỏi chỉ hai người biết để kiểm tra khéo léo, sau đó báo công an.`,
  },
  {
    id: 17,
    category: 'challenge',
    question: `Bạn đọc được bài đăng tuyển dụng công việc ở Nhật Bản và quyết định đi làm việc. Bước đầu tiên bạn làm là gì?`,
    answer: `Truy cập trang web của Cục Quản lí lao động ngoài nước, Bộ Nội vụ, dolab.molisa.gov.vn hoặc kênh chính thức hiện hành, để xem danh sách các công ty được cấp phép đưa người đi Nhật Bản.`,
  },
  {
    id: 18,
    category: 'challenge',
    question: `Kể tên một đặc điểm của những đối tượng lừa đảo tuyển dụng việc làm trên mạng xã hội?`,
    answer: `Đối tượng tuyển dụng thường dùng nick ảo, Threads hoặc Facebook mới lập. Nội dung chứa những lời chào hấp dẫn về lương, nhưng không yêu cầu kinh nghiệm, bằng cấp.`,
  },
  {
    id: 19,
    category: 'challenge',
    question: `Bạn cùng lớp đi phỏng vấn part-time ở địa chỉ lạ rồi mất liên lạc nhiều giờ, điện thoại tắt máy. Bạn sẽ làm gì?`,
    answer: `Báo ngay cho công an và nhà trường, cung cấp toàn bộ thông tin và vị trí, hoạt động của bạn ấy cho người thân để hỗ trợ tìm kiếm.`,
  },
  {
    id: 20,
    category: 'challenge',
    question: `Một người quen online dụ bạn gửi ảnh riêng tư rồi đe dọa phát tán để ép bạn đi làm hoặc ra nước ngoài. Bạn sẽ làm gì?`,
    answer: `Tuyệt đối không làm theo; lưu lại bằng chứng, chặn tài khoản, báo ngay cho công an vì đây là hành vi ép buộc, khống chế, có dấu hiệu mua bán người.`,
  },
  {
    id: 21,
    category: 'challenge',
    question: `Bạn bị giữ tại cơ sở lao động trá hình, có người canh; khi có cơ hội ngắn tiếp cận cửa sổ hoặc điện thoại, bạn sẽ làm gì để trốn thoát an toàn?`,
    answer: `Tranh thủ lúc không bị chú ý để gửi vị trí cầu cứu, tạo tín hiệu kín đáo, quan sát thời điểm sơ hở để thoát và đến ngay công an gần nhất.`,
  },
  {
    id: 22,
    category: 'challenge',
    question: `Bạn thấy tin tuyển dụng "Mang thai hộ, đẻ thuê giá cao tại nước ngoài". Đây là dấu hiệu gì?`,
    answer: `Mang thai hộ trái phép có thể khiến bạn mắc kẹt ở nước ngoài, mất quyền nuôi con, đối mặt rủi ro pháp lý và tổn hại sức khỏe; dù hợp pháp ở vài nơi, đây vẫn không phải con đường an toàn.`,
  },
  {
    id: 23,
    category: 'challenge',
    question: `Bạn bè rủ rê: "Vượt biên qua đường tiểu ngạch cho đỡ tốn tiền visa". Bạn sẽ làm gì?`,
    answer: `NGUY HIỂM. Đi đường tiểu ngạch không được pháp luật bảo vệ, dễ bị bắt cóc, bán người hoặc tai nạn.`,
  },
  {
    id: 24,
    category: 'challenge',
    question: `Công ty tuyển dụng nói: "Thu hộ chiếu để quản lý nhân sự". Đúng hay sai?`,
    answer: `SAI LUẬT. Người lao động có quyền giữ hộ chiếu của mình. Chỉ cơ quan xuất nhập cảnh mới có quyền thu giữ trong trường hợp cụ thể.`,
  },
  {
    id: 25,
    category: 'challenge',
    question: `Gia đình nhận được điện thoại yêu cầu chuyển 200 triệu tiền chuộc con từ Campuchia về. Gia đình nên làm gì?`,
    answer: `BÁO CÔNG AN. Ghi âm cuộc gọi, giữ lại tin nhắn tống tiền, số tài khoản của kẻ tống tiền để cung cấp cho công an. Không tự ý chuyển tiền ngay.`,
  },
  {
    id: 26,
    category: 'challenge',
    question: `Nhà tuyển dụng ngân hàng Vietcombank yêu cầu bạn đọc mô tả công việc qua link http://job-info-secure123.xyz/update/file. Bạn sẽ làm gì?`,
    answer: `KHÔNG CLICK. Link lạ có thể chứa mã độc đánh cắp tài khoản hoặc định vị; thường có tên miền lạ, chuỗi ký tự dài hoặc kỳ quặc, không phải Google Drive, OneDrive, LinkedIn hay website chính thức.`,
  },
  {
    id: 27,
    category: 'challenge',
    question: `Bạn làm việc tại quán ăn, chủ quán giữ hết tiền bo và lương, không cho nghỉ giải lao. Đây là tình huống gì và bạn nên làm gì?`,
    answer: `Bạn đang bị cưỡng bức lao động. Hãy tìm cách gọi Tổng đài quốc gia về phòng, chống mua bán người 111 hoặc nhờ khách hàng tin cậy báo công an.`,
  },
  {
    id: 28,
    category: 'challenge',
    question: `Tài xế xe ôm ở bến xe đề nghị: "Lên xe này đi, chở về đâu chú chở rẻ hơn trên app nhé". Bạn sẽ làm gì?`,
    answer: `TỪ CHỐI. Không đi nhờ xe người lạ tại các khu vực nhạy cảm như bến xe, cửa khẩu.`,
  },
  {
    id: 29,
    category: 'challenge',
    question: `Nhà tuyển dụng mời làm PG sự kiện "việc nhẹ, lương cao" 3-5 triệu một buổi nhưng địa điểm là quán karaoke. Bạn sẽ làm gì?`,
    answer: `CẢNH GIÁC. Nạn nhân được đưa tới quán karaoke hoặc khách sạn, bị giữ điện thoại và ép phục vụ tình dục. Đây thường là các tụ điểm mại dâm trá hình hoặc bóc lột tình dục.`,
  },
  {
    id: 30,
    category: 'challenge',
    question: `Bạn đã trốn thoát khỏi nơi giam giữ. Bạn cần làm gì ngay lập tức?`,
    answer: `Tìm đến đồn cảnh sát địa phương hoặc Đại sứ quán Việt Nam. Không quay lại lấy đồ đạc.`,
  },
  {
    id: 31,
    category: 'challenge',
    question: `Bạn bè rủ đi làm việc nhưng dặn: "Đừng nói cho bố mẹ biết, để bố mẹ bất ngờ khi mang tiền về". Đây là dấu hiệu gì?`,
    answer: `DẤU HIỆU LỪA ĐẢO. Kẻ xấu luôn muốn cô lập bạn khỏi gia đình để dễ bề kiểm soát.`,
  },
  {
    id: 32,
    category: 'challenge',
    question: `Công việc yêu cầu bạn tạo nhiều tài khoản Facebook giả để kết bạn với người lạ. Đây là dấu hiệu gì?`,
    answer: `Bạn đang bị ép tham gia vào đường dây lừa đảo trực tuyến. Đây là hành vi phạm pháp.`,
  },
  {
    id: 33,
    category: 'challenge',
    question: `Người yêu qua mạng 2 tháng rủ bạn sang sống chung ở Vinhomes Ocean Park, hứa sẽ lo toàn bộ tài chính và giấy tờ. Bạn sẽ làm gì?`,
    answer: `TỪ CHỐI. Mối quan hệ qua mạng 2 tháng là không đủ tin cậy. Việc hứa lo toàn bộ tài chính và giấy tờ tạo sự lệ thuộc nguy hiểm. Sống chung ở nơi kín, xa gia đình khiến ta gần như không có bảo vệ pháp lý.`,
  },
  {
    id: 34,
    category: 'challenge',
    question: `Nhà tuyển dụng bảo bạn "lên xe riêng của công ty đi về văn phòng phỏng vấn", bạn có nên lên không?`,
    answer: `KHÔNG. "Lên xe riêng của công ty" trước khi xác minh được văn phòng là dấu hiệu rủi ro. Bạn mất quyền kiểm soát lộ trình, không biết điểm đến thật, dễ bị đưa đi nơi khác.`,
  },
  {
    id: 35,
    category: 'challenge',
    question: `Bạn thấy một phụ nữ mang thai bị nhóm người giám sát chặt chẽ tại bệnh viện gần biên giới. Bạn sẽ làm gì?`,
    answer: `Ghi nhớ đặc điểm, biển số xe và báo ngay cho bảo vệ bệnh viện hoặc công an 113. Có thể là đường dây mua bán bào thai.`,
  },
  {
    id: 36,
    category: 'challenge',
    question: `Bạn nhận được lời mời: "Sang Myanmar làm việc IT, lương cứng 1000$". Bạn không biết tiếng Anh hoặc IT. Đây là dấu hiệu gì?`,
    answer: `LỪA ĐẢO 100%. Không có công ty IT nào tuyển người không có chuyên môn với mức lương đó. Bạn có thể bị bán vào các khu lừa đảo.`,
  },
  {
    id: 37,
    category: 'challenge',
    question: `Trước khi ra nước ngoài làm việc, bạn cần lưu số điện thoại nào trong danh bạ, đặt tên ẩn danh, để bí mật liên lạc khi gặp nguy hiểm?`,
    answer: `Số Đại sứ quán Việt Nam tại nước đó và số Tổng đài bảo hộ công dân Việt Nam ở nước ngoài +844.62.844.844.`,
  },
  {
    id: 38,
    category: 'challenge',
    question: `Kẻ bắt cóc ép bạn gọi về nhà nói dối là "Con đang làm việc tốt, đừng lo". Bạn làm sao để ra tín hiệu?`,
    answer: `Dùng mật mã gia đình nếu đã thống nhất trước, hoặc nói những thông tin sai lệch hiển nhiên, ví dụ hỏi thăm sức khỏe người đã mất, để gia đình nghi ngờ.`,
  },
  {
    id: 39,
    category: 'challenge',
    question: `Bạn thấy quảng cáo: "Xóa nợ xấu, vay tiền nhanh, chỉ cần làm việc đơn giản để trừ nợ". Đây là dấu hiệu gì?`,
    answer: `BẪY. Đây là bẫy lao động khổ sai. Bạn sẽ trở thành nạn nhân của di cư bất hợp pháp, bị bóc lột thậm tệ và có nguy cơ bị mua bán trái phép.`,
  },
  {
    id: 40,
    category: 'challenge',
    question: `Bạn đã an toàn trở về sau khi bị mua bán. Bạn nên liên hệ ai để được hỗ trợ?`,
    answer: `Liên hệ đường dây nóng 111 để tìm hỗ trợ từ IOM, Ngôi Nhà Bình Yên của Hội Liên hiệp Phụ nữ Việt Nam, Hagar Việt Nam. Cục Bảo trợ Xã hội, Sở Y tế, Sở Nội vụ có thể hỗ trợ y tế, pháp lý, tái hòa nhập, học nghề.`,
  },
  {
    id: 41,
    category: 'challenge',
    question: `Bạn nhận lời làm việc cho một shop thời trang online. Studio yêu cầu giữ CMND và điện thoại trước khi bạn livestream. Bạn sẽ làm gì?`,
    answer: `TỪ CHỐI NGAY. Tuyệt đối không giao CMND hay điện thoại vì đó là dấu hiệu bóc lột và giam giữ.`,
  },
  {
    id: 42,
    category: 'challenge',
    question: `Bạn là sinh viên năm nhất đang đi tìm trọ. Một người đàn ông đến dãy trọ nói: "Anh có phòng trọ rẻ hơn, gần trường, đi xem thử." Bạn sẽ làm gì?`,
    answer: `Từ chối đi theo, chỉ xem trọ qua chủ nhà có thông tin rõ ràng; nhắn chủ trọ hoặc tòa nhà kiểm tra đối tượng.`,
  },
  {
    id: 43,
    category: 'challenge',
    question: `Một người gọi nói: "Người thân của bạn bị tai nạn, có người của bệnh viện đến đón bạn đi xử lý giấy tờ." Bạn sẽ làm gì?`,
    answer: `Không đi theo, tự gọi cho người thân, bệnh viện hoặc 115 để xác minh; báo nhà trọ hoặc bảo vệ nếu có người đến đón.`,
  },
  {
    id: 44,
    category: 'challenge',
    question: `Bạn đi workshop kỹ năng nhưng phát hiện bị giữ điện thoại, ép ký vay tiền hoặc làm đa cấp trong phòng kín. Bạn sẽ làm gì?`,
    answer: `Lập tức tìm cách rời khỏi phòng. Nếu bị giữ, gọi 113 hoặc 111, báo cho trường và công an khu vực. Sau khi ra ngoài, báo cho công an và cảnh báo bạn bè về địa điểm này.`,
  },
  {
    id: 45,
    category: 'challenge',
    question: `Một người trên Tinder/Bumble hẹn gặp ở ngoại ô hoặc khu công nghiệp, hẹn đón bạn bằng xe ô tô riêng. Đây có thể là dấu hiệu gì?`,
    answer: `Nguy cơ lừa đảo. Không đi hoặc chỉ gặp lần đầu ở nơi đông người, có bạn biết vị trí bạn đang ở.`,
  },
  {
    id: 46,
    category: 'challenge',
    question: `Công ty môi giới đưa cho bạn hộ chiếu không đúng tên để qua biên giới. Bạn sẽ làm gì?`,
    answer: `Từ chối ngay và rời khỏi; báo cơ quan chức năng hoặc 111, giữ hộ chiếu thật của mình.`,
  },
  {
    id: 47,
    category: 'challenge',
    question: `Hướng dẫn viên bảo: "Qua cửa khẩu phải nói là đi du lịch, không được nói đi làm". Bạn sẽ làm gì?`,
    answer: `Tách khỏi đoàn bằng cách viện cớ quay lại lấy giấy tờ hoặc đi vệ sinh, tách khỏi nhóm và báo cho biên phòng hoặc công an vì bị ép khai gian khi xuất cảnh là dấu hiệu của xuất cảnh trái phép.`,
  },
  {
    id: 48,
    category: 'challenge',
    question: `Bạn bị dẫn ra biên giới với lý do việc lương cao, bị thu điện thoại, ép ký nợ; khi xe dừng đổ xăng cửa mở bạn có vài chục giây, bạn sẽ làm gì để thoát?`,
    answer: `Tranh thủ lúc cửa mở chạy thẳng đến nơi có đông người như trạm xăng, quầy thu ngân, kêu cứu lớn, nhờ họ gọi công an; tuyệt đối không quay lại, không thương lượng và không lấy đồ đạc.`,
  },
  {
    id: 49,
    category: 'challenge',
    question: `Một tư vấn du học yêu cầu nộp hộ chiếu gốc và 500 USD để "giữ chỗ học bổng" nhưng không có giấy tờ chính thức. Bạn sẽ làm gì?`,
    answer: `Không nộp bất kỳ giấy tờ hay tiền nào; kiểm tra qua kênh chính thống hoặc liên hệ trực tiếp trường.`,
  },
  {
    id: 50,
    category: 'challenge',
    question: `Bạn đi tour đường bộ sang Trung Quốc nhưng bị tách xe trung chuyển với lý do giao thông. Bạn sẽ làm gì?`,
    answer: `Giả vờ cần đi vệ sinh hoặc buồn nôn để xe buộc phải dừng, rồi nhanh chóng đi vào nơi có người và gọi 111 hoặc công an để báo nguy hiểm.`,
  },
  {
    id: 51,
    category: 'challenge',
    question: `Bạn trốn thoát khỏi động mại dâm nhưng không có tiền, không giấy tờ, đang ở nước ngoài. Bạn tin ai?`,
    answer: `TÌM CẢNH SÁT hoặc cơ quan đại diện ngoại giao Việt Nam như Đại sứ quán, Lãnh sự quán. Tránh tin người lạ, taxi hoặc xe ôm tự phát vì có thể là người dụ lại. Hãy tìm nơi đông người hoặc mượn điện thoại gọi về Việt Nam theo cú pháp +84 và số người thân.`,
  },
  {
    id: 52,
    category: 'challenge',
    question: `Bạn bị lừa khi đi du lịch, bị thu giấy tờ và nghi bị gắn định vị; khi được xuống xe đi vệ sinh, bạn chỉ có vài phút. Bạn sẽ làm gì?`,
    answer: `Giấu hoặc loại bỏ thiết bị theo dõi, tìm đến những cơ quan thực thi pháp luật như công an cửa khẩu, bộ đội biên phòng, hoặc những nơi công cộng để xin sự trợ giúp.`,
  },
  {
    id: 53,
    category: 'challenge',
    question: `Bạn đứng ở cổng trường, bị người lạ áp sát; sau đó chóng mặt, buồn nôn, tê tay dù không ăn uống gì, nghi bị dùng chất gây mê. Bạn chỉ còn vài chục giây. Bạn sẽ làm gì?`,
    answer: `Lập tức rời xa người đó, chạy về phía đông người hoặc bảo vệ trường, kêu cứu lớn; nếu còn cầm điện thoại thì gọi 113. Tuyệt đối không để họ dìu đi hoặc chạm vào người bạn.`,
  },
  {
    id: 54,
    category: 'challenge',
    question: `Bạn vào thang máy ký túc xá với người lạ, họ áp sát làm rơi khăn giấy gần mặt khiến bạn chóng mặt khó thở, thang còn vài tầng, bạn sẽ làm gì?`,
    answer: `Giữ khoảng cách tối đa, che miệng mũi bằng tay áo, bấm tất cả các tầng để cửa mở càng sớm càng tốt và lao ra ngoài kêu cứu.`,
  },
  {
    id: 55,
    category: 'challenge',
    question: `Ở sân bay, một người nhờ bạn "cầm hộ vali vì họ quá cân", không cho bạn mở xem bên trong. Bạn sẽ làm gì?`,
    answer: `TỪ CHỐI. Bạn có thể bị lợi dụng vận chuyển ma túy hoặc các vật dụng, chất cấm trái pháp luật. Đây là một tội danh nghiêm trọng nên tuyệt đối không cầm những thứ mà mình không biết rõ.`,
  },
  {
    id: 56,
    category: 'challenge',
    question: `Một người gọi video tự xưng công an, gửi "lệnh bắt" và yêu cầu bạn khóa cửa phòng, không được liên hệ ai. Họ nói bạn đang bị điều tra. Bạn sẽ làm gì?`,
    answer: `Tắt cuộc gọi ngay để tránh bị định vị; không làm theo bất kỳ yêu cầu nào; gọi 113 hoặc đến công an địa phương để xác minh. Công an thật không yêu cầu tự nhốt mình hay liên lạc qua mạng xã hội.`,
  },
  {
    id: 57,
    category: 'challenge',
    question: `Bạn nhận video call từ mẹ, nói bạn đến ngay một địa điểm vắng để giúp việc khẩn cấp. Giọng giống, mặt giống nhưng linh cảm không ổn. Bạn sẽ làm gì?`,
    answer: `Gọi trực tiếp vào số thật của người thân để kiểm tra; tuyệt đối không đi đến nơi đó. Deepfake có thể làm giả hoàn toàn hình ảnh và giọng nói.`,
  },
  {
    id: 58,
    category: 'challenge',
    question: `Bạn bị nhốt trong cốp xe, bị chuyển qua nhiều xe để tránh phát hiện. Bạn có thể làm gì để tăng cơ hội được tìm thấy?`,
    answer: `Bạn nên tạo dấu vết như xé áo hoặc giấy, nhét qua khe cốp; cố tình làm rơi đồ cá nhân dọc đường; hoặc gõ vào thành xe theo nhịp để gây chú ý khi xe dừng.`,
  },
  {
    id: 59,
    category: 'challenge',
    question: `Bạn là nạn nhân mua bán người, bị nhốt trong phòng kín và canh giữ, vừa tỉnh dậy mơ màng. Bạn phải làm gì để giữ tỉnh táo và thu thập thông tin?`,
    answer: `Bạn hãy tập trung vào âm thanh xung quanh, xác định nhiều hay ít người. Nhớ thời điểm đưa cơm, tiếng khóa mở cửa, vì đó là thời cơ thoát. Cố gắng uống nước sạch nếu có để giảm tác dụng thuốc mê.`,
  },
  {
    id: 60,
    category: 'challenge',
    question: `Bạn bị ép làm việc 15-18 tiếng, bị bỏ đói và bị đánh nếu phản kháng. Làm sao duy trì sức để chờ cơ hội trốn?`,
    answer: `Ăn bất cứ thứ gì có thể như bánh mì, mì gói, nước đường. Tuyệt đối không chống trả để tránh bị thương nặng. Quan sát ca gác và ghi nhớ thời gian đối tượng mệt nhất.`,
  },
  {
    id: 61,
    category: 'challenge',
    question: `Bạn bị đưa lên xe "việc lương cao" nhưng xe đổi hướng, tắt GPS, yêu cầu tắt điện thoại và nói sắp qua biên giới. Bạn sẽ làm gì?`,
    answer: `Hãy cố gắng giữ lại thiết bị cá nhân như điện thoại, thẻ SIM. Gửi tin nhắn cho người thân: vị trí cuối cùng, biển số xe, tên người dẫn. Tránh chống trả, tập trung ghi nhớ thông tin quan trọng.`,
  },
  {
    id: 62,
    category: 'challenge',
    question: `Bạn bị giam trong phòng và bị ép gọi video hoặc điện thoại về Việt Nam để lừa người thân hoặc người khác. Bạn từ chối thì sẽ bị đánh. Bạn phải làm gì?`,
    answer: `Kéo dài thời gian bằng cách giả vờ mạng yếu, cố ý làm sai để bị coi thường; lợi dụng lúc được ra ngoài để trốn, báo tin. Nếu buộc phải làm, không cung cấp thông tin thật và dùng ám hiệu để bên kia biết bạn đang gặp nguy hiểm.`,
  },
  {
    id: 63,
    category: 'challenge',
    question: `Bạn bị nhốt cùng nhiều người, bị ép gia nhập nhóm để đánh nhau hoặc canh giữ; từ chối thì bị đánh. Bạn sẽ làm gì?`,
    answer: `Hãy tỏ ra yếu thế, không hữu ích, để họ ít chú ý. Bạn có thể làm quen với nạn nhân khác để tự bảo vệ, quan sát sơ hở của kẻ gác để thoát. Tuyệt đối không tham gia bạo lực.`,
  },
  {
    id: 64,
    category: 'challenge',
    question: `Người yêu mới quen rủ về quê ra mắt nhưng đường đi ngày càng hẻo lánh, gần biên giới và yêu cầu băng đường mòn sang "bên kia". Bạn sẽ làm gì?`,
    answer: `DỪNG LẠI. Đây là thủ đoạn điển hình bán phụ nữ sang biên giới. Tuyệt đối không bước qua cột mốc biên giới. Giả vờ đau bụng dữ dội hoặc say xe đòi xuống. Gọi điện thoại báo vị trí ngay cho gia đình.`,
  },
  {
    id: 65,
    category: 'challenge',
    question: `Bạn được tuyển làm phục vụ nhưng bị đưa đến khu nhà tối, ép làm việc cả ngày và cấm liên lạc gia đình. Bạn sẽ làm gì?`,
    answer: `Nên từ chối; quan sát kỹ môi trường, địa chỉ, người xung quanh và lối thoát. Khi có cơ hội, liên lạc gia đình, bạn bè hoặc công an để được hỗ trợ; không đồng ý làm việc khi bị giam giữ, cô lập.`,
  },
  {
    id: 66,
    category: 'challenge',
    question: `Bạn đi phỏng vấn ở quán cà phê vắng, bị ép lên xe, giật điện thoại và xe chạy về phía biên giới. Bạn sẽ làm gì?`,
    answer: `Giữ bình tĩnh, quan sát đường đi, thời điểm xe dừng hoặc giảm tốc. Gây chú ý để được người ngoài nhìn thấy như gõ cửa, ném vật ra ngoài. Nếu còn điện thoại, nhắn tin cho người thân hoặc gọi 113 ngay, cung cấp vị trí hiện tại.`,
  },
  {
    id: 67,
    category: 'challenge',
    question: `Bạn dự tiệc, uống đồ người khác đưa; tỉnh dậy ở nhà gần biên giới, mất điện thoại/ví và có người canh cửa. Bạn sẽ làm gì?`,
    answer: `Giữ bình tĩnh và quan sát xung quanh. Tìm các vật dụng có thể dùng để gây chú ý. Nếu có thể, di chuyển đến nơi đông người hoặc có camera. Liên lạc, gọi cho cảnh sát, người thân. Không hoảng loạn, luôn xem xét kỹ trước khi hành động.`,
  },
  {
    id: 68,
    category: 'challenge',
    question: `Một tổ chức từ thiện lạ mặt đến bản làng, đề nghị đưa các bé gái 12-14 tuổi về thành phố "học nghề và nuôi ăn học miễn phí". Đây là dấu hiệu gì?`,
    answer: `NGUY CƠ CAO LÀ ĐƯỜNG DÂY MUA BÁN NGƯỜI. Cần xác minh giấy phép của tổ chức này với chính quyền xã. Nhiều kẻ buôn người núp bóng từ thiện để bắt trẻ em về làm giúp việc hoặc bóc lột tình dục.`,
  },
  {
    id: 69,
    category: 'challenge',
    question: `Tại sân bay quốc tế, một người lạ nhờ bạn: "Dẫn đứa bé này qua cửa an ninh giúp, mẹ nó đang bận xách đồ phía sau". Bạn sẽ làm gì?`,
    answer: `KHÔNG GIÚP. Bạn có thể vô tình tiếp tay cho tội phạm mua bán trẻ em hoặc vận chuyển ma túy giấu trong đồ đạc của trẻ.`,
  },
  {
    id: 70,
    category: 'challenge',
    question: `Bạn thấy một nhóm người nước ngoài đang lôi kéo một phụ nữ Việt Nam lên xe ô tô, cô ấy khóc nhưng không dám la hét. Bạn sẽ làm gì?`,
    answer: `HÔ HOÁN hoặc QUAY PHIM. Hô to để thu hút sự chú ý của đám đông, quay phim lại nếu an toàn làm bằng chứng và báo công an ngay lập tức.`,
  },
  {
    id: 71,
    category: 'challenge',
    question: `Một spa hoặc thẩm mỹ viện tuyển học viên: "Đào tạo miễn phí, bao ăn ở, cam kết việc làm lương cao sau khi học xong". Đây là dấu hiệu gì?`,
    answer: `CẨN TRỌNG. Nhiều cơ sở trá hình dùng chiêu này để ép học viên ký hợp đồng nợ học phí, sau đó bắt làm mại dâm để trả nợ.`,
  },
  {
    id: 72,
    category: 'challenge',
    question: `Bạn đang chat với nhân viên tư vấn xuất khẩu lao động, họ nói: "Zalo này bị theo dõi, em chuyển sang Telegram bật chế độ tin nhắn tự xóa để trao đổi cho kín". Đây là dấu hiệu gì?`,
    answer: `DẤU HIỆU LỪA ĐẢO. Những công ty làm ăn đàng hoàng không bao giờ yêu cầu dùng tin nhắn tự xóa. Họ muốn xóa bằng chứng lừa đảo.`,
  },
  {
    id: 73,
    category: 'challenge',
    question: `Bạn đi du lịch đường bộ sang Lào, người dẫn đường đòi giữ hộ chiếu và bảo bạn đi không qua cửa an ninh. Đây là dấu hiệu gì?`,
    answer: `LỪA ĐẢO. Bạn không bao giờ được tách rời hộ chiếu tại cửa khẩu. Hắn cầm hộ chiếu để khống chế bạn ở đầu bên kia biên giới.`,
  },
  {
    id: 74,
    category: 'challenge',
    question: `Chủ sử dụng lao động giam lỏng bạn, nhưng vẫn cho bạn dùng Facebook để làm việc lừa đảo. Bạn cầu cứu thế nào cho an toàn?`,
    answer: `Đổi tên hiển thị Facebook thành một cái tên bình thường, tham gia các hội nhóm "Người Việt tại..." và nhắn tin xin giúp đỡ vào khung giờ chủ lơ là như đêm khuya hoặc giờ ăn. Nhớ xóa tin nhắn ngay sau khi gửi.`,
  },
  {
    id: 75,
    category: 'challenge',
    question: `Gia đình hàng xóm của bạn có ý định muốn cho con gái nhỏ đi làm con nuôi người nước ngoài vì họ hứa cho nhiều tiền. Đây là dấu hiệu gì?`,
    answer: `CÓ THỂ LÀ MUA BÁN TRẺ EM. Việc cho nhận con nuôi phải qua Sở Tư pháp hoặc Cục Con nuôi đúng quy trình. Nhận tiền trực tiếp là hành vi bán con phạm pháp.`,
  },
  {
    id: 76,
    category: 'challenge',
    question: `Bạn bị giữ ở biên giới vì giấy tờ có vấn đề. Một người lạ đến thì thầm: "Đưa anh 5 triệu, anh dắt đi đường rừng qua chốt". Bạn sẽ làm gì?`,
    answer: `TỪ CHỐI. Đi theo họ bạn sẽ mất sự bảo vệ của pháp luật, dễ bị cướp, hiếp hoặc bán sang bên kia biên giới. Hãy giải quyết minh bạch với biên phòng.`,
  },
  {
    id: 77,
    category: 'challenge',
    question: `Nếu nghi ngờ một cơ sở massage hoặc karaoke đang giam giữ người trái phép, bạn nên làm gì để đảm bảo an toàn cho mình khi tố giác?`,
    answer: `Gọi Tổng đài quốc gia về phòng, chống mua bán người 111 hoặc gửi đơn nặc danh, sử dụng sim rác để báo tin cho công an. Không trực tiếp đến đó quay phim, chụp ảnh gây nguy hiểm cho bản thân.`,
  },
  {
    id: 78,
    category: 'challenge',
    question: `Khi đi du lịch nước ngoài một mình, bạn nên để giấy tờ tùy thân ở đâu?`,
    answer: `Chia làm hai nơi: bản gốc cất trong két sắt khách sạn hoặc túi an toàn sát người. Chỉ mang theo bản photo hoặc ảnh chụp khi đi dạo phố để tránh bị giật mất cả giấy tờ lẫn tiền.`,
  },
  {
    id: 79,
    category: 'challenge',
    question: `Một người phụ nữ trong xóm rủ bạn: "Cô đang mang thai, sang Trung Quốc đẻ rồi cho con nuôi, họ bồi dưỡng 100 triệu, về vẫn khỏe re". Đây là hành vi gì?`,
    answer: `MUA BÁN NGƯỜI DƯỚI 16 TUỔI. Hành vi bán bào thai hoặc trẻ sơ sinh là tội phạm mua bán người. Bạn có thể bị giữ lại làm máy đẻ hoặc bị xâm hại sức khỏe.`,
  },
  {
    id: 80,
    category: 'challenge',
    question: `Bạn là người dân tộc thiểu số, có người lạ đến bản rủ đi làm công ty dưới xuôi, trả trước cho bố mẹ 20 triệu tiền mặt. Đây là dấu hiệu gì?`,
    answer: `MUA BÁN NGƯỜI DẠNG "TRẢ TRƯỚC". Nhận tiền nghĩa là bạn đã bị bán. Bạn sẽ bị cưỡng bức lao động để trừ nợ số tiền đó gấp nhiều lần.`,
  },
  {
    id: 81,
    category: 'challenge',
    question: `Tại công ty môi giới ở Mỹ, hợp đồng ghi mức đãi ngộ 30.000 mỗi tháng và yêu cầu nộp đầy đủ giấy tờ tùy thân, bằng cấp. Bạn có sẵn sàng ký hợp đồng này không? Vì sao?`,
    answer: `Tuyệt đối không ký vì đây là bẫy pháp lý thường gặp ở các đơn vị lừa đảo. Hợp đồng không ghi rõ đơn vị tiền tệ là hành động cố ý gây bất lợi cho người lao động, vi phạm Điều 21 Bộ luật Lao động 2019.`,
  },
  {
    id: 82,
    category: 'challenge',
    question: `Chỗ làm của bạn thỏa thuận trả lương 2 tháng một lần và cam kết sẽ trả đủ số tiền. Bạn có đồng ý không?`,
    answer: `Không chấp nhận trả lương 2 tháng một lần: theo Điều 97 Bộ luật Lao động 2019, lương phải trả ít nhất mỗi tháng; trả chậm là trái luật, tiềm ẩn rủi ro không được thanh toán, cần từ chối để bảo vệ quyền lợi.`,
  },
  {
    id: 83,
    category: 'challenge',
    question: `Bạn được đào tạo tiếng miễn phí nhưng phải ký cam kết làm việc 2 năm, nghỉ sớm phải đền 80 triệu. Bạn có đồng ý không? Nếu không, giải pháp của bạn là gì?`,
    answer: `Điều 62 Bộ luật Lao động 2019 chỉ cho hoàn trả chi phí đào tạo có chứng từ. Nếu phải bồi thường khi nghỉ việc thì việc phạt hợp đồng là trái luật, vô hiệu.`,
  },
  {
    id: 84,
    category: 'challenge',
    question: `Trên hợp đồng của bạn có ghi lương NET 1.200 USD, không có thêm bất cứ ghi chú hay giải thích gì thêm. Đây là dấu hiệu gì?`,
    answer: `Đây là rủi ro pháp lý cho người lao động. Việc chỉ ghi "lương NET 1.200 USD" mà không giải thích quy đổi, thuế, bảo hiểm hay trách nhiệm khấu trừ là thiếu minh bạch.`,
  },
];

export default questionBank;
