const knowledgeCards = [
  {
    id: 1,
    category: 'Cơ quan, tổ chức, hiệp hội liên quan',
    title: 'Tổ chức Di cư Quốc tế (IOM) Việt Nam',
    content: 'Hà Nội (+84) 862 890 906; TP.HCM (+84) 90 300 5210 (Zalo/WhatsApp). Cung cấp thông tin di cư an toàn, hồi hương và hỗ trợ nạn nhân mua bán người.',
  },
  {
    id: 2,
    category: 'Cơ quan, tổ chức, hiệp hội liên quan',
    title: 'NCA - Hiệp hội an ninh mạng quốc gia',
    content: 'Số điện thoại: 02462600626. Tổ chức xã hội nghề nghiệp của công dân và tổ chức Việt Nam hoạt động trong an ninh mạng.',
  },
  {
    id: 3,
    category: 'Cơ quan, tổ chức, hiệp hội liên quan',
    title: 'Blue Dragon Children’s Foundation - Tổ chức Rồng xanh vì trẻ em',
    content: 'Cứu hộ, trao sức mạnh cho những người bị mua bán, bóc lột, đặc biệt là trẻ em.',
  },
  {
    id: 4,
    category: 'Cơ quan, tổ chức, hiệp hội liên quan',
    title: 'UNICEF Việt Nam',
    content: 'Quỹ Nhi đồng Liên hợp quốc tại Việt Nam hoạt động vì quyền trẻ em và phục vụ cộng đồng, trong đó bao gồm vấn nạn mua bán người. ĐT: +84 (024) 3.850.0100 (Hà Nội), +84 (028) 3.821.9413 (HCM).',
  },
  {
    id: 5,
    category: 'Cơ quan, tổ chức, hiệp hội liên quan',
    title: 'UNODC - Cơ quan Phòng chống Ma túy và Tội phạm của Liên Hợp Quốc',
    content: 'ĐT: +84 (024) 3.850.0100 (Hà Nội), +84 (028) 3.821.9413 (HCM).',
  },
  {
    id: 6,
    category: 'Cơ quan, tổ chức, hiệp hội liên quan',
    title: 'Hagar Việt Nam',
    content: 'SĐT: 1900 969 680. Hỗ trợ người chịu ảnh hưởng của sang chấn tâm lý do nạn mua bán người, bạo lực và xâm hại.',
  },
  {
    id: 7,
    category: 'Cơ quan, tổ chức, hiệp hội liên quan',
    title: 'Cục Quản lý lao động ngoài nước (DOLAB)',
    content: '(84-4) 38249517.',
  },
  {
    id: 8,
    category: 'Cơ quan, tổ chức, hiệp hội liên quan',
    title: 'Tổ chức Tầm nhìn Thế giới (World Vision) tại Việt Nam',
    content: 'Trao quyền cho cộng đồng và phối hợp với chính phủ, góp phần chấm dứt nạn mua bán người.',
  },
  {
    id: 9,
    category: 'Cơ quan, tổ chức, hiệp hội liên quan',
    title: 'Trung Tâm Lao Động Ngoài Nước COLAB',
    content: 'Trung tâm lao động ngoài nước COLAB.',
  },
  {
    id: 10,
    category: 'Đường dây nóng',
    title: 'Tổng đài bảo hộ công dân Bộ Ngoại giao Việt Nam',
    content: '0084.981.84.84.84.',
  },
  {
    id: 11,
    category: 'Đường dây nóng',
    title: 'Tổng đài Quốc gia về phòng, chống mua bán người',
    content: '111.',
  },
  {
    id: 12,
    category: 'Đường dây nóng',
    title: 'Đường dây nóng Cục quản lý lao động ngoài nước',
    content: '0243 824 9517.',
  },
  {
    id: 13,
    category: 'Đường dây nóng',
    title: 'Ngôi nhà bình yên',
    content: 'Thuộc Trung tâm hỗ trợ phụ nữ phát triển, 1900.969.680.',
  },
  {
    id: 14,
    category: 'Đường dây nóng',
    title: 'Blue Dragon Children’s Foundation',
    content: '0243 717 2307.',
  },
  {
    id: 15,
    category: 'Đường dây nóng',
    title: 'Hagar Việt Nam',
    content: '0943 111 967.',
  },
  {
    id: 16,
    category: 'Đường dây nóng',
    title: 'Cục quản lý lao động ngoài nước',
    content: '(84-24) 38249517.',
  },
  {
    id: 17,
    category: 'Đường dây nóng',
    title: 'Trung tâm lao động ngoài nước (COLAB)',
    content: '02473030199.',
  },
  {
    id: 18,
    category: 'Định nghĩa mua bán người',
    title: 'Mua bán người là gì?',
    content: 'Mua bán người là hành vi tuyển mộ, vận chuyển, chuyển giao, chứa chấp hoặc tiếp nhận người để bóc lột (lao động cưỡng bức, mại dâm, khổ sai, lấy bộ phận cơ thể, v.v.).',
  },
  {
    id: 19,
    category: 'Các lĩnh vực hoạt động của MBN',
    title: 'Bóc lột tình dục',
    content: 'Nạn nhân bị ép buộc mại dâm, trở thành nô lệ tình dục, bị cưỡng ép quan hệ tình dục, tham gia sản xuất nội dung khiêu dâm hoặc bị ép đẻ thuê vì mục đích trục lợi, xâm phạm nghiêm trọng nhân phẩm và sức khỏe.',
  },
  {
    id: 20,
    category: 'Các lĩnh vực hoạt động của MBN',
    title: 'Hôn nhân trái pháp luật, kết hôn có yếu tố nước ngoài',
    content: 'Nạn nhân bị ép làm vợ/chồng nhằm mục đích bóc lột tình dục, sức lao động hoặc sinh sản, không có sự tự nguyện, bị cô lập, bạo lực và tước đoạt quyền cá nhân.',
  },
  {
    id: 21,
    category: 'Các lĩnh vực hoạt động của MBN',
    title: 'Mua bán bào thai, thai nhi, trẻ sơ sinh',
    content: 'Các đối tượng tổ chức mua bán, trao đổi bào thai, thai nhi hoặc trẻ sơ sinh nhằm trục lợi, vi phạm nghiêm trọng quyền trẻ em và đạo đức xã hội.',
  },
  {
    id: 22,
    category: 'Các lĩnh vực hoạt động của MBN',
    title: 'Lấy bộ phận cơ thể và các mục đích vô nhân đạo khác',
    content: 'Bao gồm thu hoạch nội tạng trái phép, cưỡng ép gây tổn hại thể chất, mua bán bào thai/trẻ sơ sinh, nhận con nuôi trái luật hoặc khai thác sinh sản vì trục lợi.',
  },
  {
    id: 23,
    category: 'Các lĩnh vực hoạt động của MBN',
    title: 'Cưỡng ép thực hiện hành vi phạm tội',
    content: 'Nạn nhân bị ép tham gia lừa đảo, đánh bạc, cho vay nặng lãi, cưỡng đoạt, vận chuyển hàng cấm hoặc các hoạt động phạm pháp khác cho đường dây tội phạm.',
  },
  {
    id: 24,
    category: 'Các lĩnh vực hoạt động của MBN',
    title: 'Các hoạt động phạm pháp khác',
    content: 'Lừa đảo chiếm đoạt tài sản; tổ chức hoặc tham gia đánh bạc; xuất khẩu lao động trái phép; cho vay nặng lãi, cưỡng đoạt tài sản và các hoạt động phạm pháp khác.',
  },
  {
    id: 25,
    category: 'Các phương thức, thủ đoạn MBN',
    title: 'Phương thức mua bán người theo Luật Phòng, chống mua bán người (2024)',
    content: 'Bao gồm vũ lực, đe dọa, bắt cóc, lừa gạt, cưỡng ép, gian lận, lạm dụng quyền lực, lợi dụng tình trạng dễ bị tổn thương của nạn nhân.',
  },
  {
    id: 26,
    category: 'Các phương thức, thủ đoạn MBN',
    title: 'Thủ đoạn ngụy trang',
    content: 'Các thủ đoạn mua bán người được ngụy trang dưới hình thức việc làm, kết hôn, xuất khẩu lao động, du học, nhận nuôi, hoặc môi giới dịch vụ.',
  },
  {
    id: 27,
    category: 'Dấu hiệu nhận biết',
    title: 'Công ty lừa đảo môi giới đi lao động nước ngoài: hợp đồng sai lệch',
    content: 'Dùng thông tin sai lệch, sơ sài trong hợp đồng ký kết và đặt người lao động vào nguy cơ vi phạm pháp luật.',
  },
  {
    id: 28,
    category: 'Dấu hiệu nhận biết',
    title: 'Công ty lừa đảo môi giới đi lao động nước ngoài: thiếu giấy xác nhận',
    content: 'Thiếu các loại giấy xác nhận, cam kết với người lao động. Đừng vội đóng tiền cho công ty nếu thấy những phiếu thu thiếu thông tin, đáng ngờ.',
  },
  {
    id: 29,
    category: 'Dấu hiệu nhận biết',
    title: 'Sử dụng visa không hợp pháp để lao động',
    content: 'Các công ty lừa đảo thường dùng visa tôn giáo (không dành cho lao động) để đưa người ra nước ngoài làm việc, khiến lao động rơi vào tình trạng cư trú trái phép, dễ bị bóc lột và đe dọa.',
  },
  {
    id: 30,
    category: 'Dấu hiệu nhận biết',
    title: 'Visa tôn giáo',
    content: 'Visa tôn giáo là thị thực cấp cho người nhập cảnh để thực hiện hoạt động tôn giáo (truyền đạo, tu học, sinh hoạt tôn giáo), không dùng cho lao động hay mục đích thương mại.',
  },
  {
    id: 31,
    category: 'Dấu hiệu tin tuyển dụng giả',
    title: 'Công việc mập mờ, lương cao bất thường',
    content: 'Thông tin công việc mập mờ, không rõ ràng về công ty tuyển dụng, không yêu cầu bằng cấp nhưng mức lương lại cao bất thường.',
  },
  {
    id: 32,
    category: 'Dấu hiệu tin tuyển dụng giả',
    title: 'Phải đóng tiền nhiều lần',
    content: 'Phải đóng tiền nhiều lần, đến nhiều cơ sở khác nhau để phỏng vấn.',
  },
  {
    id: 33,
    category: 'Dấu hiệu tin tuyển dụng giả',
    title: 'Biên nhận thiếu dấu mộc',
    content: 'Các giấy tờ biên nhận từ công ty không có giấy mộc, không tiến hành ký hợp đồng thử việc.',
  },
  {
    id: 34,
    category: 'Dấu hiệu tin tuyển dụng giả',
    title: 'Đổi địa chỉ thường xuyên',
    content: 'Công ty thường xuyên đổi địa chỉ, nơi phỏng vấn trông rất tạm bợ.',
  },
  {
    id: 35,
    category: 'Dấu hiệu tin tuyển dụng giả',
    title: 'Né tránh hoặc dọa nạt',
    content: 'Thái độ né tránh hoặc dọa nạt trong lúc trao đổi khi người tìm việc hỏi kỹ hơn về nội dung công việc, công ty.',
  },
  {
    id: 36,
    category: 'Dấu hiệu tin tuyển dụng giả',
    title: 'Từ ngữ dụ dỗ quen thuộc',
    content: 'Thường dùng những từ ngữ: việc nhẹ lương cao, vào làm ngay, đi làm ngay, không có phí môi giới, v.v. để miêu tả về công việc.',
  },
  {
    id: 37,
    category: 'Dấu hiệu tin tuyển dụng giả',
    title: 'Không tìm thấy email liên hệ',
    content: 'Gặp khó khăn khi tìm kiếm hoặc không thể tìm thấy email liên hệ của công ty tuyển dụng.',
  },
  {
    id: 38,
    category: 'Mua bán người trên không gian mạng',
    title: 'Mua bán người trên không gian mạng',
    content: 'Hành vi này lợi dụng tính ẩn danh, khả năng kết nối xuyên biên giới, phương tiện giao tiếp số và nền tảng mạng xã hội để dụ dỗ, tuyển mộ, lừa gạt, môi giới mua bán người.',
  },
  {
    id: 39,
    category: 'Mua bán người trên không gian mạng',
    title: 'Đối tượng nạn nhân dễ ảnh hưởng nhất',
    content: 'Phụ nữ, học sinh, sinh viên và trẻ em là nhóm dễ bị tổn thương nhất, thường bị lừa qua mạng xã hội.',
  },
  {
    id: 40,
    category: 'Mua bán người trên không gian mạng',
    title: 'Bắt cóc online',
    content: 'Bắt cóc online là thủ đoạn lừa đảo công nghệ cao, dùng thông tin cá nhân để đe dọa, ép nạn nhân cắt liên lạc, tạo video giả bị bắt cóc nhằm tống tiền hoặc phục vụ mua bán người, lao động cưỡng bức.',
  },
  {
    id: 41,
    category: 'Mua bán người trên không gian mạng',
    title: 'Thủ đoạn bắt cóc online phổ biến',
    content: 'Giả mạo công an/tòa án, dựng cáo buộc và bằng chứng giả; ép nạn nhân giữ bí mật, di chuyển nơi kín, cung cấp ảnh/video nhạy cảm rồi tống tiền gia đình.',
  },
  {
    id: 42,
    category: '“6 Không” phòng tránh MBN qua mạng',
    title: 'Không tiếp tục cuộc gọi bất thường',
    content: 'Không tiếp tục cuộc gọi khi phát hiện dấu hiệu bất thường hoặc nguy cơ lừa đảo; hãy chấm dứt liên lạc ngay để tránh bị lợi dụng.',
  },
  {
    id: 43,
    category: '“6 Không” phòng tránh MBN qua mạng',
    title: 'Không giao dịch với tài khoản không rõ danh tính',
    content: 'Không giao dịch với các tài khoản không rõ danh tính; đồng thời sử dụng mật khẩu mạnh và bật xác minh hai bước để bảo vệ tài khoản cá nhân.',
  },
  {
    id: 44,
    category: '“6 Không” phòng tránh MBN qua mạng',
    title: 'Không tin lời mời gọi phi thực tế',
    content: 'Không tin vào những lời mời gọi phi thực tế như “việc nhẹ lương cao”, quà tặng giá trị hay cơ hội nổi tiếng nhanh chóng trên mạng.',
  },
  {
    id: 45,
    category: '“6 Không” phòng tránh MBN qua mạng',
    title: 'Không gửi thông tin cá nhân',
    content: 'Không gửi thông tin cá nhân như địa chỉ nhà, số CCCD/CMND, trường học hay thông tin gia đình cho người lạ trong môi trường trực tuyến.',
  },
  {
    id: 46,
    category: '“6 Không” phòng tránh MBN qua mạng',
    title: 'Không gặp trực tiếp một mình',
    content: 'Không gặp gỡ trực tiếp một mình khi làm quen qua mạng; hãy thông báo cho người thân, chọn nơi công cộng và đi cùng bạn bè.',
  },
  {
    id: 47,
    category: '“6 Không” phòng tránh MBN qua mạng',
    title: 'Không im lặng khi bị đe dọa',
    content: 'Không im lặng khi bị đe dọa, quấy rối hay tống tiền; hãy lưu giữ bằng chứng (tin nhắn, ảnh chụp màn hình, âm thanh) và báo ngay cho cơ quan chức năng để được hỗ trợ kịp thời.',
  },
  {
    id: 48,
    category: 'Xu hướng và thủ đoạn trên không gian mạng',
    title: 'Chuyển từ trực tiếp sang trực tuyến',
    content: 'Tội phạm có xu hướng chuyển từ tiếp cận trực tiếp sang trực tuyến để giảm rủi ro bị phát hiện; lợi dụng không gian mạng để ẩn danh và dụ dỗ nạn nhân.',
  },
  {
    id: 49,
    category: 'Xu hướng và thủ đoạn trên không gian mạng',
    title: 'Thủ đoạn tuyển dụng việc nhẹ lương cao',
    content: 'Đăng tin “việc nhẹ, lương cao”, “xuất khẩu lao động dễ dàng”, tiếp cận người tìm việc, rồi yêu cầu chuyển phí, giấy tờ, lừa gạt.',
  },
  {
    id: 50,
    category: 'Xu hướng và thủ đoạn trên không gian mạng',
    title: 'Thủ đoạn môi giới hôn nhân quốc tế / lấy chồng nước ngoài',
    content: 'Hứa hẹn hôn nhân với người nước ngoài, hoặc môi giới kết hôn, rồi chuyển người sang nước ngoài dưới vỏ bọc hôn nhân.',
  },
  {
    id: 51,
    category: 'Xu hướng và thủ đoạn trên không gian mạng',
    title: 'Lừa đảo xuyên biên giới / ép gia nhập đường dây lừa đảo trực tuyến',
    content: 'Nạn nhân được dụ tham gia các công việc như đầu tư, kinh doanh, marketing online; sau đó bị ép tham gia các đường dây vi phạm pháp luật.',
  },
  {
    id: 52,
    category: 'Xu hướng và thủ đoạn trên không gian mạng',
    title: 'Sử dụng mạng xã hội, ứng dụng hẹn hò',
    content: 'Kết bạn, tán tỉnh, tạo lòng tin, sau đó mời “gặp mặt”, “đi chơi”, rồi bắt cóc hoặc dụ dỗ đi nơi khác.',
  },
  {
    id: 53,
    category: 'Xu hướng và thủ đoạn trên không gian mạng',
    title: 'Tài khoản ẩn danh, giả danh, mã hóa, chuyển tiền điện tử',
    content: 'Các đối tượng sử dụng tài khoản ảo, VPN, mã hóa thông điệp, thanh toán bằng tiền mã hóa để che dấu dấu vết.',
  },
  {
    id: 54,
    category: 'Cách xử trí',
    title: 'Khi biết mình bị mua bán',
    content: 'Hãy giữ bình tĩnh, xác định vị trí, lưu lại thông tin liên quan và tranh thủ cơ hội tìm giúp đỡ hoặc thoát thân. Báo ngay cơ quan chức năng hoặc gọi 113, 111; tránh hoảng loạn và liên hệ người thân khi có thể.',
  },
  {
    id: 55,
    category: 'Cách xử trí',
    title: 'Khi phát hiện trường hợp bị mua bán',
    content: 'Hãy thu thập thông tin cần thiết và báo ngay cho cơ quan chức năng hoặc gọi 113, 111. Không tự ý can thiệp; phối hợp với chính quyền để đảm bảo an toàn và ngăn chặn tội phạm.',
  },
  {
    id: 56,
    category: 'Dấu hiệu hợp đồng lừa đảo khi lao động tại nước ngoài',
    title: 'Không ghi rõ tên pháp nhân đầy đủ',
    content: 'Không ghi rõ tên pháp nhân đầy đủ, mã số doanh nghiệp, chỉ ghi tên, chi nhánh, hoặc cá nhân môi giới. Điều 21 Bộ luật Lao động 2019 quy định hợp đồng phải ghi rõ người sử dụng lao động, lương, BHXH,...',
  },
  {
    id: 57,
    category: 'Dấu hiệu hợp đồng lừa đảo khi lao động tại nước ngoài',
    title: 'Ràng buộc nghĩa vụ một chiều',
    content: 'Người lao động bị ràng buộc nghĩa vụ, phạt, bồi thường rõ ràng trong khi doanh nghiệp không có trách nhiệm khi vi phạm. Điều 15 Bộ luật Lao động 2019 quy định hợp đồng phải tự nguyện, bình đẳng, trung thực, không trái pháp luật, cấm phân biệt đối xử.',
  },
  {
    id: 58,
    category: 'Dấu hiệu hợp đồng lừa đảo khi lao động tại nước ngoài',
    title: 'Điều khoản địa điểm làm việc mơ hồ',
    content: 'Điều khoản mơ hồ như “địa điểm làm việc theo nhu cầu doanh nghiệp” dễ bị lạm dụng để điều người lao động sang việc nặng nhọc, nguy hiểm. Điều 21 Bộ luật Lao động 2019: Hợp đồng lao động phải có đủ thông tin về công việc và địa điểm làm việc.',
  },
  {
    id: 59,
    category: 'Dấu hiệu hợp đồng lừa đảo khi lao động tại nước ngoài',
    title: 'Không quy định rõ tiền lương thực nhận',
    content: 'Không quy định rõ tiền lương thực nhận mà chỉ ghi lương “dự kiến”, “trung bình”, “chưa khấu trừ”. Điều 21 Bộ luật Lao động 2019: Hợp đồng lao động phải có đầy đủ thông tin về công việc và địa điểm làm việc.',
  },
  {
    id: 60,
    category: 'Dấu hiệu hợp đồng lừa đảo khi lao động tại nước ngoài',
    title: 'Thiếu cơ chế chấm dứt hợp đồng hợp pháp',
    content: 'Chỉ ghi trường hợp người lao động vi phạm và không bao gồm các quyền đơn phương chấm dứt hợp đồng hợp pháp. Điều 35 Bộ luật Lao động 2019: Người lao động có quyền đơn phương chấm dứt hợp đồng nhưng phải báo trước theo thời hạn luật định.',
  },
  {
    id: 61,
    category: 'Dấu hiệu hợp đồng lừa đảo khi lao động tại nước ngoài',
    title: 'Hạn chế quyền khiếu nại, tố cáo',
    content: 'Hợp đồng bao gồm điều khoản hạn chế quyền cơ bản như cấm khiếu nại, tố cáo. Theo Nghị định 24/2018/NĐ-CP, người lao động có quyền khiếu nại và yêu cầu giải quyết các vấn đề vi phạm pháp luật về lao động.',
  },
  {
    id: 62,
    category: 'Dấu hiệu hợp đồng lừa đảo khi lao động tại nước ngoài',
    title: 'Không có hoặc ghi không rõ ràng về bảo hiểm',
    content: 'Không nêu loại bảo hiểm, đơn vị chi trả, phạm vi. Nghị định 44/2013/NĐ-CP quy định về bảo hiểm tai nạn lao động và bảo hiểm y tế cho người lao động.',
  },
  {
    id: 63,
    category: 'Dấu hiệu hợp đồng lừa đảo khi lao động tại nước ngoài',
    title: 'Thúc đẩy việc ký nhanh và tạo áp lực',
    content: 'Điều 10 Bộ luật Lao động 2019 nhấn mạnh nguyên tắc tự nguyện, bình đẳng, thiện chí và trung thực khi giao kết hợp đồng, cấm ép buộc, gây sức ép.',
  },
];

export default knowledgeCards;
